title: My Title
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: Overview
    link: '/pages/10-intro/00-index.html'
  - name: Strategies
    link: '/pages/strategies.html'

